#Position	Attribute   Value   Code

noun_type = [
(	0	,	'CATEGORY'	,	'Noun'	,	'N'	),
(	1	,	'Type'	,	'common'	,	'c'	),
(	1	,	'Type'	,	'proper'	,	'p'	),
(	2	,	'Gender'	,	'masculine'	,	'm'	),
(	2	,	'Gender'	,	'feminine'	,	'f'	),
(	2	,	'Gender'	,	'neuter'	,	'n'	),
(	3	,	'Number'	,	'singular'	,	's'	),
(	3	,	'Number'	,	'plural'	,	'p'	),
(	4	,	'Case'	,	'vocative'	,	'v'	),
(	4	,	'Case'	,	'direct'	,	'r'	),
(	4	,	'Case'	,	'oblique'	,	'o'	),
(	5	,	'Definiteness'	,	'no'	,	'n'	),
(	5	,	'Definiteness'	,	'yes'	,	'y'	),
(	6	,	'Clitic'	,	'no'	,	'n'	),
(	6	,	'Clitic'	,	'yes'	,	'y'	)]

verb_type = [
(	0	,	'CATEGORY'	,	'Verb'	,	'V'	),
(	1	,	'Type'	,	'main'	,	'm'	),
(	1	,	'Type'	,	'auxiliary'	,	'a'	),
(	1	,	'Type'	,	'modal'	,	'o'	),
(	1	,	'Type'	,	'copula'	,	'c'	),
(	2	,	'VForm'	,	'indicative'	,	'i'	),
(	2	,	'VForm'	,	'subjunctive'	,	's'	),
(	2	,	'VForm'	,	'imperative'	,	'm'	),
(	2	,	'VForm'	,	'infinitive'	,	'n'	),
(	2	,	'VForm'	,	'participle'	,	'p'	),
(	2	,	'VForm'	,	'gerund'	,	'g'	),
(	3	,	'Tense'	,	'present'	,	'p'	),
(	3	,	'Tense'	,	'imperfect'	,	'i'	),
(	3	,	'Tense'	,	'past'	,	's'	),
(	3	,	'Tense'	,	'pluperfect'	,	'l'	),
(	4	,	'Person'	,	'first'	,	'1'	),
(	4	,	'Person'	,	'second'	,	'2'	),
(	4	,	'Person'	,	'third'	,	'3'	),
(	5	,	'Number'	,	'singular'	,	's'	),
(	5	,	'Number'	,	'plural'	,	'p'	),
(	6	,	'Gender'	,	'masculine'	,	'm'	),
(	6	,	'Gender'	,	'feminine'	,	'f'	),
(	6	,	'Gender'	,	'neuter'	,	'n'	),
(	10	,	'Clitic'	,	'no'	,	'n'	),
(	10	,	'Clitic'	,	'yes'	,	'y'	)]

adj_type = [
(	0	,	'CATEGORY'	,	'Adjective'	,	'A'	),
(	1	,	'Type'	,	'qualificative'	,	'f'	),
(	2	,	'Degree'	,	'positive'	,	'p'	),
(	2	,	'Degree'	,	'comparative'	,	'c'	),
(	2	,	'Degree'	,	'superlative'	,	's'	),
(	3	,	'Gender'	,	'masculine'	,	'm'	),
(	3	,	'Gender'	,	'feminine'	,	'f'	),
(	3	,	'Gender'	,	'neuter'	,	'n'	),
(	4	,	'Number'	,	'singular'	,	's'	),
(	4	,	'Number'	,	'plural'	,	'p'	),
(	5	,	'Case'	,	'vocative'	,	'v'	),
(	5	,	'Case'	,	'direct'	,	'r'	),
(	5	,	'Case'	,	'oblique'	,	'o'	),
(	6	,	'Definiteness'	,	'no'	,	'n'	),
(	6	,	'Definiteness'	,	'yes'	,	'y'	),
(	7	,	'Clitic'	,	'no'	,	'n'	),
(	7	,	'Clitic'	,	'yes'	,	'y'	),
]

pron_type = [
(	0	,	'CATEGORY'	,	'Pronoun'	,	'P'	),
(	1	,	'Type'	,	'personal'	,	'p'	),
(	1	,	'Type'	,	'demonstrative'	,	'd'	),
(	1	,	'Type'	,	'indefinite'	,	'i'	),
(	1	,	'Type'	,	'possessive'	,	's'	),
(	1	,	'Type'	,	'reflexive'	,	'x'	),
(	1	,	'Type'	,	'negative'	,	'z'	),
(	1	,	'Type'	,	'int-rel'	,	'w'	),
(	2	,	'Person'	,	'first'	,	'1'	),
(	2	,	'Person'	,	'second'	,	'2'	),
(	2	,	'Person'	,	'third'	,	'3'	),
(	3	,	'Gender'	,	'masculine'	,	'm'	),
(	3	,	'Gender'	,	'feminine'	,	'f'	),
(	3	,	'Gender'	,	'neuter'	,	'n'	),
(	4	,	'Number'	,	'singular'	,	's'	),
(	4	,	'Number'	,	'plural'	,	'p'	),
(	5	,	'Case'	,	'nominative'	,	'n'	),
(	5	,	'Case'	,	'genitive'	,	'g'	),
(	5	,	'Case'	,	'dative'	,	'd'	),
(	5	,	'Case'	,	'accusative'	,	'a'	),
(	5	,	'Case'	,	'vocative'	,	'v'	),
(	5	,	'Case'	,	'direct'	,	'r'	),
(	5	,	'Case'	,	'oblique'	,	'o'	),
(	6	,	'Owner_Number'	,	'singular'	,	's'	),
(	6	,	'Owner_Number'	,	'plural'	,	'p'	),
(	8	,	'Clitic'	,	'no'	,	'n'	),
(	8	,	'Clitic'	,	'yes'	,	'y'	),
(	14	,	'Pronoun_Form'	,	'strong'	,	's'	),
(	14	,	'Pronoun_Form'	,	'weak'	,	'w'	),
]

det_type = [
(	0	,	'CATEGORY'	,	'Determiner'	,	'D'	),
(	1	,	'Type'	,	'demonstrative'	,	'd'	),
(	1	,	'Type'	,	'indefinite'	,	'i'	),
(	1	,	'Type'	,	'possessive'	,	's'	),
(	1	,	'Type'	,	'int-rel'	,	'w'	),
(	1	,	'Type'	,	'negative'	,	'z'	),
(	1	,	'Type'	,	'emphatic'	,	'h'	),
(	2	,	'Person'	,	'first'	,	'1'	),
(	2	,	'Person'	,	'second'	,	'2'	),
(	2	,	'Person'	,	'third'	,	'3'	),
(	3	,	'Gender'	,	'masculine'	,	'm'	),
(	3	,	'Gender'	,	'feminine'	,	'f'	),
(	3	,	'Gender'	,	'neuter'	,	'n'	),
(	4	,	'Number'	,	'singular'	,	's'	),
(	4	,	'Number'	,	'plural'	,	'p'	),
(	5	,	'Case'	,	'direct'	,	'r'	),
(	5	,	'Case'	,	'oblique'	,	'o'	),
(	6	,	'Owner_Number'	,	'singular'	,	's'	),
(	6	,	'Owner_Number'	,	'plural'	,	'p'	),
(	8	,	'Clitic'	,	'no'	,	'n'	),
(	8	,	'Clitic'	,	'yes'	,	'y'	),
(	9	,	'Modific_Type'	,	'prenomin'	,	'e'	),
(	9	,	'Modific_Type'	,	'postnomin'	,	'o'	),
]
art_type = [
(	0	,	'CATEGORY'	,	'Article'	,	'T'	),
(	1	,	'Type'	,	'definite'	,	'f'	),
(	1	,	'Type'	,	'indefinite'	,	'i'	),
(	1	,	'Type'	,	'possessive'	,	's'	),
(	1	,	'Type'	,	'demonstrative'	,	'd'	),
(	2	,	'Gender'	,	'masculine'	,	'm'	),
(	2	,	'Gender'	,	'feminine'	,	'f'	),
(	2	,	'Gender'	,	'neuter'	,	'n'	),
(	3	,	'Number'	,	'singular'	,	's'	),
(	3	,	'Number'	,	'plural'	,	'p'	),
(	4	,	'Case'	,	'direct'	,	'r'	),
(	4	,	'Case'	,	'oblique'	,	'o'	),
(	5	,	'Clitic'	,	'no'	,	'n'	),
(	5	,	'Clitic'	,	'yes'	,	'y'	),]

adv_type = [
(	0	,	'CATEGORY'	,	'Adverb'	,	'R'	),
(	1	,	'Type'	,	'general'	,	'g'	),
(	1	,	'Type'	,	'particle'	,	'p'	),
(	1	,	'Type'	,	'negative'	,	'z'	),
(	1	,	'Type'	,	'modifier'	,	'm'	),
(	1	,	'Type'	,	'int-rel'	,	'w'	),
(	1	,	'Type'	,	'portmanteau'	,	'c'	),
(	2	,	'Degree'	,	'positive'	,	'p'	),
(	2	,	'Degree'	,	'comparative'	,	'c'	),
(	2	,	'Degree'	,	'superlative'	,	's'	),
(	3	,	'Clitic'	,	'no'	,	'n'	),
(	3	,	'Clitic'	,	'yes'	,	'y'	),
]

adp_type = [
(	0	,	'CATEGORY'	,	'Adposition'	,	'S'	),
(	1	,	'Type'	,	'preposition'	,	'p'	),
(	2	,	'Formation'	,	'simple'	,	's'	),
(	2	,	'Formation'	,	'compound'	,	'c'	),
(	3	,	'Case'	,	'genitive'	,	'g'	),
(	3	,	'Case'	,	'dative'	,	'd'	),
(	3	,	'Case'	,	'accusative'	,	'a'	),
(	4	,	'Clitic'	,	'no'	,	'n'	),
(	4	,	'Clitic'	,	'yes'	,	'y'	),
]

conj_type = [
(	0	,	'CATEGORY'	,	'Conjunction'	,	'C'	),
(	1	,	'Type'	,	'coordinating'	,	'c'	),
(	1	,	'Type'	,	'subordinating'	,	's'	),
(	1	,	'Type'	,	'portmanteau'	,	'r'	),
(	2	,	'Formation'	,	'simple'	,	's'	),
(	2	,	'Formation'	,	'compound'	,	'c'	),
(	3	,	'Coord_Type'	,	'simple'	,	's'	),
(	3	,	'Coord_Type'	,	'repetit'	,	'r'	),
(	3	,	'Coord_Type'	,	'correlat'	,	'c'	),
(	4	,	'Sub_Type'	,	'negative'	,	'z'	),
(	4	,	'Sub_Type'	,	'positive'	,	'p'	),
(	5	,	'Clitic'	,	'no'	,	'n'	),
(	5	,	'Clitic'	,	'yes'	,	'y'	),
]

num_type = [
(	0	,	'CATEGORY'	,	'Numeral'	,	'M'	),
(	1	,	'Type'	,	'cardinal'	,	'c'	),
(	1	,	'Type'	,	'ordinal'	,	'o'	),
(	1	,	'Type'	,	'fractal'	,	'f'	),
(	1	,	'Type'	,	'multiple'	,	'm'	),
(	1	,	'Type'	,	'collect'	,	'l'	),
(	2	,	'Gender'	,	'masculine'	,	'm'	),
(	2	,	'Gender'	,	'feminine'	,	'f'	),
(	2	,	'Gender'	,	'neuter'	,	'n'	),
(	3	,	'Number'	,	'singular'	,	's'	),
(	3	,	'Number'	,	'plural'	,	'p'	),
(	4	,	'Case'	,	'direct'	,	'r'	),
(	4	,	'Case'	,	'oblique'	,	'o'	),
(	5	,	'Form'	,	'digit'	,	'd'	),
(	5	,	'Form'	,	'roman'	,	'r'	),
(	5	,	'Form'	,	'letter'	,	'l'	),
(	5	,	'Form'	,	'both'	,	'b'	),
(	6	,	'Definiteness'	,	'no'	,	'n'	),
(	6	,	'Definiteness'	,	'yes'	,	'y'	),
(	7	,	'Clitic'	,	'no'	,	'n'	),
(	7	,	'Clitic'	,	'yes'	,	'y'	),
]

part_type = [
(	0	,	'CATEGORY'	,	'Particle'	,	'Q'	),
(	1	,	'Type'	,	'negative'	,	'z'	),
(	1	,	'Type'	,	'infinitive'	,	'n'	),
(	1	,	'Type'	,	'subjunctive'	,	's'	),
(	1	,	'Type'	,	'aspect'	,	'a'	),
(	1	,	'Type'	,	'future'	,	'f'	),
(	3	,	'Clitic'	,	'no'	,	'n'	),
(	3	,	'Clitic'	,	'yes'	,	'y'	),
]

abbrev_type = [
(	0	,	'CATEGORY'	,	'Abbreviation'	,	'Y'	),
(	1	,	'Syntactic_Type'	,	'nominal'	,	'n'	),
(	1	,	'Syntactic_Type'	,	'verbal'	,	'v'	),
(	1	,	'Syntactic_Type'	,	'adjectival'	,	'a'	),
(	1	,	'Syntactic_Type'	,	'adverbial'	,	'r'	),
(	1	,	'Syntactic_Type'	,	'pronominal'	,	'p'	),
(	2	,	'Gender'	,	'masculine'	,	'm'	),
(	2	,	'Gender'	,	'feminine'	,	'f'	),
(	2	,	'Gender'	,	'neuter'	,	'n'	),
(	3	,	'Number'	,	'singular'	,	's'	),
(	3	,	'Number'	,	'plural'	,	'p'	),
(	4	,	'Case'	,	'direct'	,	'r'	),
(	4	,	'Case'	,	'oblique'	,	'o'	),
(	4	,	'Case'	,	'vocative'	,	'v'	),
(	5	,	'Definiteness'	,	'yes'	,	'y'	),
(	5	,	'Definiteness'	,	'no'	,	'n'	),
]

interj_type = [
(	0	,	'CATEGORY'	,	'Interjection'	,	'I'	),
]

residual_type = [
(	0	,	'CATEGORY'	,	'Residual'	,	'X'	),
]

punct_type = [
(   0, 'CATEGORY',  	'Punctuation',  	'Z')
]

msd_to_upos_dict = {
  'Nc':  'NOUN',
  'Np':  'PROPN',
  'Vm':  'VERB',
  'Vo':  'VERB',
  'Va':  'AUX',
  'Vc':  'VERB',
  'A':  'ADJ',
  'P':  'PRON',
  'D':  'DET',
  'T':  'DET',
  'R':  'ADV',
  'S':  'ADP',
  'Cc':  'CCONJ',
  'Cr':  'CCONJ', # și - portmanteau
  'Cs':  'SCONJ',
  'M':  'NUM',
  'Q':  'PART',
  'I':  'INTJ',
  'Y':  'SYM',
  'X':  'X',
  'Z': 'PUNCT'}
